ruby '~> 3.0'
source 'https://rubygems.org'

gem 'json' # required for bibtex

gem 'asciidoctor', '~> 2.0'
gem 'asciidoctor-pdf', '~> 2.3'
gem 'asciidoctor-bibtex', '~> 0.8.0'
# gem 'asciidoctor-interdoc-reftext', '~> 0.5.2'
gem 'asciidoctor-interdoc-reftext', git: 'https://github.com/lonkaars/asciidoctor-interdoc-reftext'

