:document: Handover
include::share/meta.adoc[]

=== A Note Before Reading
The team of year 2023-2024 consisted of only software students, meaning no 
hardware was developed in this year. We were tasked with simplifying the 
software to the point where it would only have to be ported into the new hardware,
which was designed in the year 2022-2023. The goal of this year would be to create
a software framework which can be used to implement new puzzles and to make the 
development process of these puzzles easier. 

== Project State
The current project state is as follows: No new hardware has been designed
or developed this year. The software was completely revised, now consisting of a 
main controller, and multiple puzzle modules. The main controller (a RPI Pico W) 
can interact with the different puzzle modules using an I^2^C bus.

== What Went Wrong

== Recommendations
kijk naar de documentatie maar verifieer alles op het laagste niveau

Voor de volgende jaren: maak zo snel mogelijk prototypes, laat zien dat *iets* werkt

ER MOET ONDERZOCHT WORDEN NAAR MULTIMASTER CONTROLLERS DIE OOK ALS SLAVE KUNNEN WORDEN GEADDRESSEERD (INTENS MOEILIJK TE VINDEN)

i2c MOET, arbitration moet, Atmega328p zou geschikt zijn voor losse puzzelmodules

--
Maak een duidelijke waarschuwing"
- ga er niet van uit dat je het al weet, doe ff wat low level research over de onderwerpen

rpi heeft programmable io modules, mogelijk via deze omweg rp2040 wel als MULTIMASTER met slave adresseerbaar
- rp2040 kan alleen 7-bit adressen hebben
include::share/footer.adoc[]
